/* tslint:disable */
/* eslint-disable */
/**
 * Web Event Clock API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ClockChannel } from '../models';
// @ts-ignore
import type { ResponsePayload } from '../models';
// @ts-ignore
import type { SetRequestPayload } from '../models';
// @ts-ignore
import type { SetResponsePayload } from '../models';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Publish a time event to a channel
         * @param {ClockChannel} channel 
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPublishChannelPost: async (channel: ClockChannel, setRequestPayload: SetRequestPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('apiPublishChannelPost', 'channel', channel)
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiPublishChannelPost', 'setRequestPayload', setRequestPayload)
            const localVarPath = `/api/publish/{channel}`
                .replace('{channel}', encodeURIComponent(String(channel)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Set the main clock (absolute mode)
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSetClockPost: async (setRequestPayload: SetRequestPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiSetClockPost', 'setRequestPayload', setRequestPayload)
            const localVarPath = `/api/set.clock`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Start the timer (relative mode)
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStartTimerPost: async (setRequestPayload: SetRequestPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiStartTimerPost', 'setRequestPayload', setRequestPayload)
            const localVarPath = `/api/start.timer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Stop the timer
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStopTimerPost: async (setRequestPayload: SetRequestPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiStopTimerPost', 'setRequestPayload', setRequestPayload)
            const localVarPath = `/api/stop.timer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Subscribe to a clock event channel
         * @param {ClockChannel} channel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSubscribeChannelPost: async (channel: ClockChannel, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('apiSubscribeChannelPost', 'channel', channel)
            const localVarPath = `/api/subscribe/{channel}`
                .replace('{channel}', encodeURIComponent(String(channel)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unsubscribe from a clock event channel
         * @param {ClockChannel} channel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUnsubscribeChannelPost: async (channel: ClockChannel, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('apiUnsubscribeChannelPost', 'channel', channel)
            const localVarPath = `/api/unsubscribe/{channel}`
                .replace('{channel}', encodeURIComponent(String(channel)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Publish a time event to a channel
         * @param {ClockChannel} channel 
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPublishChannelPost(channel: ClockChannel, setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetResponsePayload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPublishChannelPost(channel, setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiPublishChannelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Set the main clock (absolute mode)
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSetClockPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetResponsePayload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSetClockPost(setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSetClockPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Start the timer (relative mode)
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiStartTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetResponsePayload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiStartTimerPost(setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiStartTimerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Stop the timer
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiStopTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetResponsePayload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiStopTimerPost(setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiStopTimerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Subscribe to a clock event channel
         * @param {ClockChannel} channel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponsePayload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSubscribeChannelPost(channel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSubscribeChannelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Unsubscribe from a clock event channel
         * @param {ClockChannel} channel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUnsubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponsePayload>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUnsubscribeChannelPost(channel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiUnsubscribeChannelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Publish a time event to a channel
         * @param {ClockChannel} channel 
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPublishChannelPost(channel: ClockChannel, setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload> {
            return localVarFp.apiPublishChannelPost(channel, setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Set the main clock (absolute mode)
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSetClockPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload> {
            return localVarFp.apiSetClockPost(setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Start the timer (relative mode)
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStartTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload> {
            return localVarFp.apiStartTimerPost(setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Stop the timer
         * @param {SetRequestPayload} setRequestPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStopTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload> {
            return localVarFp.apiStopTimerPost(setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Subscribe to a clock event channel
         * @param {ClockChannel} channel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig): AxiosPromise<ResponsePayload> {
            return localVarFp.apiSubscribeChannelPost(channel, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unsubscribe from a clock event channel
         * @param {ClockChannel} channel 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUnsubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig): AxiosPromise<ResponsePayload> {
            return localVarFp.apiUnsubscribeChannelPost(channel, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiHealthGet(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Publish a time event to a channel
     * @param {ClockChannel} channel 
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiPublishChannelPost(channel: ClockChannel, setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload>;

    /**
     * 
     * @summary Set the main clock (absolute mode)
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiSetClockPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload>;

    /**
     * 
     * @summary Start the timer (relative mode)
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiStartTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload>;

    /**
     * 
     * @summary Stop the timer
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiStopTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig): AxiosPromise<SetResponsePayload>;

    /**
     * 
     * @summary Subscribe to a clock event channel
     * @param {ClockChannel} channel 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiSubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig): AxiosPromise<ResponsePayload>;

    /**
     * 
     * @summary Unsubscribe from a clock event channel
     * @param {ClockChannel} channel 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiUnsubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig): AxiosPromise<ResponsePayload>;

}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * 
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiHealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiHealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Publish a time event to a channel
     * @param {ClockChannel} channel 
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public async apiPublishChannelPost(channel: ClockChannel, setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiPublishChannelPost(channel, setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Set the main clock (absolute mode)
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public async apiSetClockPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSetClockPost(setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Start the timer (relative mode)
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public async apiStartTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiStartTimerPost(setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Stop the timer
     * @param {SetRequestPayload} setRequestPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public async apiStopTimerPost(setRequestPayload: SetRequestPayload, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiStopTimerPost(setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Subscribe to a clock event channel
     * @param {ClockChannel} channel 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public async apiSubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiSubscribeChannelPost(channel, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unsubscribe from a clock event channel
     * @param {ClockChannel} channel 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public async apiUnsubscribeChannelPost(channel: ClockChannel, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiUnsubscribeChannelPost(channel, options).then((request) => request(this.axios, this.basePath));
    }
}

