/* tslint:disable */
/* eslint-disable */
/**
 * Web Event Clock API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from '../base';
/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHealthGet: async (options = {}) => {
            const localVarPath = `/api/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Publish a time event to a channel
         * @param {ClockChannel} channel
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPublishChannelPost: async (channel, setRequestPayload, options = {}) => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('apiPublishChannelPost', 'channel', channel);
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiPublishChannelPost', 'setRequestPayload', setRequestPayload);
            const localVarPath = `/api/publish/{channel}`
                .replace('{channel}', encodeURIComponent(String(channel)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Set the main clock (absolute mode)
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSetClockPost: async (setRequestPayload, options = {}) => {
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiSetClockPost', 'setRequestPayload', setRequestPayload);
            const localVarPath = `/api/set.clock`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Start the timer (relative mode)
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStartTimerPost: async (setRequestPayload, options = {}) => {
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiStartTimerPost', 'setRequestPayload', setRequestPayload);
            const localVarPath = `/api/start.timer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Stop the timer
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStopTimerPost: async (setRequestPayload, options = {}) => {
            // verify required parameter 'setRequestPayload' is not null or undefined
            assertParamExists('apiStopTimerPost', 'setRequestPayload', setRequestPayload);
            const localVarPath = `/api/stop.timer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(setRequestPayload, localVarRequestOptions, configuration);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Subscribe to a clock event channel
         * @param {ClockChannel} channel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSubscribeChannelPost: async (channel, options = {}) => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('apiSubscribeChannelPost', 'channel', channel);
            const localVarPath = `/api/subscribe/{channel}`
                .replace('{channel}', encodeURIComponent(String(channel)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Unsubscribe from a clock event channel
         * @param {ClockChannel} channel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUnsubscribeChannelPost: async (channel, options = {}) => {
            // verify required parameter 'channel' is not null or undefined
            assertParamExists('apiUnsubscribeChannelPost', 'channel', channel);
            const localVarPath = `/api/unsubscribe/{channel}`
                .replace('{channel}', encodeURIComponent(String(channel)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            localVarHeaderParameter['Accept'] = 'application/json';
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function (configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiHealthGet(options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiHealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiHealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Publish a time event to a channel
         * @param {ClockChannel} channel
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPublishChannelPost(channel, setRequestPayload, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPublishChannelPost(channel, setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiPublishChannelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Set the main clock (absolute mode)
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSetClockPost(setRequestPayload, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSetClockPost(setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSetClockPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Start the timer (relative mode)
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiStartTimerPost(setRequestPayload, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiStartTimerPost(setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiStartTimerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Stop the timer
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiStopTimerPost(setRequestPayload, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiStopTimerPost(setRequestPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiStopTimerPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Subscribe to a clock event channel
         * @param {ClockChannel} channel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiSubscribeChannelPost(channel, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiSubscribeChannelPost(channel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiSubscribeChannelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Unsubscribe from a clock event channel
         * @param {ClockChannel} channel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUnsubscribeChannelPost(channel, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUnsubscribeChannelPost(channel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiUnsubscribeChannelPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    };
};
/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration, basePath, axios) {
    const localVarFp = DefaultApiFp(configuration);
    return {
        /**
         *
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiHealthGet(options) {
            return localVarFp.apiHealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Publish a time event to a channel
         * @param {ClockChannel} channel
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPublishChannelPost(channel, setRequestPayload, options) {
            return localVarFp.apiPublishChannelPost(channel, setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Set the main clock (absolute mode)
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSetClockPost(setRequestPayload, options) {
            return localVarFp.apiSetClockPost(setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Start the timer (relative mode)
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStartTimerPost(setRequestPayload, options) {
            return localVarFp.apiStartTimerPost(setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Stop the timer
         * @param {SetRequestPayload} setRequestPayload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiStopTimerPost(setRequestPayload, options) {
            return localVarFp.apiStopTimerPost(setRequestPayload, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Subscribe to a clock event channel
         * @param {ClockChannel} channel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiSubscribeChannelPost(channel, options) {
            return localVarFp.apiSubscribeChannelPost(channel, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Unsubscribe from a clock event channel
         * @param {ClockChannel} channel
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUnsubscribeChannelPost(channel, options) {
            return localVarFp.apiUnsubscribeChannelPost(channel, options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apiHealthGet(options) {
        return DefaultApiFp(this.configuration).apiHealthGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Publish a time event to a channel
     * @param {ClockChannel} channel
     * @param {SetRequestPayload} setRequestPayload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiPublishChannelPost(channel, setRequestPayload, options) {
        return DefaultApiFp(this.configuration).apiPublishChannelPost(channel, setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Set the main clock (absolute mode)
     * @param {SetRequestPayload} setRequestPayload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiSetClockPost(setRequestPayload, options) {
        return DefaultApiFp(this.configuration).apiSetClockPost(setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Start the timer (relative mode)
     * @param {SetRequestPayload} setRequestPayload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiStartTimerPost(setRequestPayload, options) {
        return DefaultApiFp(this.configuration).apiStartTimerPost(setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Stop the timer
     * @param {SetRequestPayload} setRequestPayload
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiStopTimerPost(setRequestPayload, options) {
        return DefaultApiFp(this.configuration).apiStopTimerPost(setRequestPayload, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Subscribe to a clock event channel
     * @param {ClockChannel} channel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiSubscribeChannelPost(channel, options) {
        return DefaultApiFp(this.configuration).apiSubscribeChannelPost(channel, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Unsubscribe from a clock event channel
     * @param {ClockChannel} channel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apiUnsubscribeChannelPost(channel, options) {
        return DefaultApiFp(this.configuration).apiUnsubscribeChannelPost(channel, options).then((request) => request(this.axios, this.basePath));
    }
}
