/* tslint:disable */
/* eslint-disable */
/**
 * Web Event Clock API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SetRequestPayload {
    'time': string;
    'mode'?: Mode;
}

export const Mode = {
    absolute: 'absolute',
    relative: 'relative',
} as const;

export type Mode = typeof Mode[keyof typeof Mode];


